server:
  port: 8081

spring:
  application:
    name: aopioc‐web #指定服务名

  dubbo:
    application:
      name: consumer
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.aopioc.web
